//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWcf.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Job", Namespace="http://schemas.datacontract.org/2004/07/wcfgllib")]
    [System.SerializableAttribute()]
    public partial class Job : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int maxlvlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int minlvlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxlvl {
            get {
                return this.maxlvlField;
            }
            set {
                if ((this.maxlvlField.Equals(value) != true)) {
                    this.maxlvlField = value;
                    this.RaisePropertyChanged("maxlvl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int minlvl {
            get {
                return this.minlvlField;
            }
            set {
                if ((this.minlvlField.Equals(value) != true)) {
                    this.minlvlField = value;
                    this.RaisePropertyChanged("minlvl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Ilibjobs")]
    public interface Ilibjobs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ilibjobs/GetJobs", ReplyAction="http://tempuri.org/Ilibjobs/GetJobsResponse")]
        System.Data.DataSet GetJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ilibjobs/GetJobs", ReplyAction="http://tempuri.org/Ilibjobs/GetJobsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ilibjobs/GetJobInfo", ReplyAction="http://tempuri.org/Ilibjobs/GetJobInfoResponse")]
        WpfWcf.ServiceReference1.Job GetJobInfo(int jobid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ilibjobs/GetJobInfo", ReplyAction="http://tempuri.org/Ilibjobs/GetJobInfoResponse")]
        System.Threading.Tasks.Task<WpfWcf.ServiceReference1.Job> GetJobInfoAsync(int jobid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ilibjobs/AddJob", ReplyAction="http://tempuri.org/Ilibjobs/AddJobResponse")]
        void AddJob(WpfWcf.ServiceReference1.Job j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ilibjobs/AddJob", ReplyAction="http://tempuri.org/Ilibjobs/AddJobResponse")]
        System.Threading.Tasks.Task AddJobAsync(WpfWcf.ServiceReference1.Job j);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IlibjobsChannel : WpfWcf.ServiceReference1.Ilibjobs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IlibjobsClient : System.ServiceModel.ClientBase<WpfWcf.ServiceReference1.Ilibjobs>, WpfWcf.ServiceReference1.Ilibjobs {
        
        public IlibjobsClient() {
        }
        
        public IlibjobsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IlibjobsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IlibjobsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IlibjobsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetJobs() {
            return base.Channel.GetJobs();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetJobsAsync() {
            return base.Channel.GetJobsAsync();
        }
        
        public WpfWcf.ServiceReference1.Job GetJobInfo(int jobid) {
            return base.Channel.GetJobInfo(jobid);
        }
        
        public System.Threading.Tasks.Task<WpfWcf.ServiceReference1.Job> GetJobInfoAsync(int jobid) {
            return base.Channel.GetJobInfoAsync(jobid);
        }
        
        public void AddJob(WpfWcf.ServiceReference1.Job j) {
            base.Channel.AddJob(j);
        }
        
        public System.Threading.Tasks.Task AddJobAsync(WpfWcf.ServiceReference1.Job j) {
            return base.Channel.AddJobAsync(j);
        }
    }
}
